# all data sources we will assume to be DEFAULT_DATA_SOURCE
DEFAULT_DATA_SOURCE = "table"
COUNT_COL_NAME = "count"
X_PIXEL_SIGNAL = "xBrushPixel"
X_SELECT_SIGNAL = "xBrush"
Y_PIXEL_SIGNAL = "yBrushPixel"
Y_SELECT_SIGNAL = "yBrush"
CHART_HEIGHT = 200
CHART_INNER_HEIGHT = CHART_HEIGHT
CHART_WIDTH = 400
CHART_INNER_WIDTH = CHART_WIDTH
SELECTION_SIGNAL = "selectionRange"
X_SCALE = "xscale"
Y_SCALE = "yscale"